app: aws-node-http-api
service: multi-cage-example
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  
functions:
  register:
    handler: handler.handleRequest
    events:
      - httpApi:
          path: /
          method: post
    environment:
      EVERVAULT_API_KEY: ${env:EVERVAULT_API_KEY}
      CHECK_ENTITLEMENTS_CAGE: ${CHECK_ENTITLEMENTS_CAGE}
      VALIDATE_USER_CREDENTIALS_CAGE: ${VALIDATE_USER_CREDENTIALS_CAGE}

