app: aws-node-http-api
service: evervault-inbound-relay-example
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  evRelayExample:
    handler: handler.evRelayExample
    events:
      - httpApi:
          path: /
          method: post
